twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form/custom_layout.html.twig']
    globals:
        videoIdExtractor: '@App\Service\VideoIdExtractor'

when@test:
    twig:
        strict_variables: true
